[tool.poetry]
name = "quine"
version = "0.1.0"
description = ""
authors = ["Shogo Ujiie <shogo-ujiie@m3.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
jupyter = "^1.1.1"
art = "^6.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
